name: CIE - Continuos Integration Exploration

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
  pull_request:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy: 
      matrix:
        node-versions: [14.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      - name: Use Node.js ${{ matrix.node-version }} 
        uses: actions/setup-node@v3.1.1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Enter into ci-stydy folder
        run: |
             cd ci-study
             pwd
             ls -la
             sed -n 5,10p package.json
      - name: Setup dependencies
        run: yarn
#       - run: yarn test
      - run: yarn add -g lighthouse
#       - name: Run Lighthouse CLI Benchmark
      - run: npm run build
      - run: lhci autorun
        
